//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agress.Logic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PageStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Agress.Logic.PageStrings", typeof(PageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontering.
        /// </summary>
        public static string ExpenseClaimPage_AccountingLabel {
            get {
                return ResourceManager.GetString("ExpenseClaimPage_AccountingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raderna har sparats. Verifikationsnummer.
        /// </summary>
        public static string ExpenseClaimPage_ExpectedSaveText {
            get {
                return ResourceManager.GetString("ExpenseClaimPage_ExpectedSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reseräkning (DS).
        /// </summary>
        public static string ExpenseClaimPage_ExpectedString {
            get {
                return ResourceManager.GetString("ExpenseClaimPage_ExpectedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 - Utlägg.
        /// </summary>
        public static string ExpenseClaimPage_ExpenseTab {
            get {
                return ResourceManager.GetString("ExpenseClaimPage_ExpenseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enbart utlägg.
        /// </summary>
        public static string ExpenseClaimPage_TypeOfExpense_Expense {
            get {
                return ResourceManager.GetString("ExpenseClaimPage_TypeOfExpense_Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reseverifikation.
        /// </summary>
        public static string ExpenseClaimPrintOut_ExpectedHeading {
            get {
                return ResourceManager.GetString("ExpenseClaimPrintOut_ExpectedHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string ExpenseClaimPrintOut_PeriodAbbr {
            get {
                return ResourceManager.GetString("ExpenseClaimPrintOut_PeriodAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver.nr.
        /// </summary>
        public static string ExpenseClaimPrintOut_VoucherNoAbbr {
            get {
                return ResourceManager.GetString("ExpenseClaimPrintOut_VoucherNoAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reseräkning.
        /// </summary>
        public static string LeftMenuPage_ExpenseClaim {
            get {
                return ResourceManager.GetString("LeftMenuPage_ExpenseClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tid och utlägg.
        /// </summary>
        public static string LeftMenuPage_TimeAndExpenses {
            get {
                return ResourceManager.GetString("LeftMenuPage_TimeAndExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current session has expired.
        /// </summary>
        public static string SessionExpiryText {
            get {
                return ResourceManager.GetString("SessionExpiryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daglig tidregistrering (DS).
        /// </summary>
        public static string TimeReportPage_ExpectedTitle {
            get {
                return ResourceManager.GetString("TimeReportPage_ExpectedTitle", resourceCulture);
            }
        }
    }
}
